# Lista 2 de Sistemas Elétricos de Potência.
Este Jupyter Notebook contém alguns exemplos de como utilizar o NepoSolver para resolver a lista 2 de Sistemas Elétricos de Potência, baseado na turma de 2020.

In [2]:
import lib.nepo_tools as nepo
import numpy as np
import cmath

np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

In [4]:
#ex 9
print("EXERCICIO 9")
zbus9 = 1j*np.array([
    [0.717, 0.61, 0.533, 0.58],
    [0.61, 0.732, 0.64, 0.697],
    [0.533, 0.64, 0.717, 0.67],
    [0.58, 0.697, 0.67, 0.763]
])
nepo.Zbus_case2(zbus9, 0.5j, k=3)


EXERCICIO 9
CASO 2 - Adicionando Zb de uma nova barra p para uma barra k ja existente
Barra k = 3
Copiar coluna e linha k para coluna e linha p. Modificar o ultimo elemento, que sera:
Zkkb = Zbus[k][k] + Zb = 0.717j + 0.5j = 1.217j, onde k=3

Zbus original:
0.717/_90.0°  0.61/_90.0°  0.533/_90.0°  0.58/_90.0°  
0.61/_90.0°  0.732/_90.0°  0.64/_90.0°  0.697/_90.0°  
0.533/_90.0°  0.64/_90.0°  0.717/_90.0°  0.67/_90.0°  
0.58/_90.0°  0.697/_90.0°  0.67/_90.0°  0.763/_90.0°  

Zbus modificado:
0.717/_90.0°  0.61/_90.0°  0.533/_90.0°  0.58/_90.0°  0.533/_90.0°  
0.61/_90.0°  0.732/_90.0°  0.64/_90.0°  0.697/_90.0°  0.64/_90.0°  
0.533/_90.0°  0.64/_90.0°  0.717/_90.0°  0.67/_90.0°  0.717/_90.0°  
0.58/_90.0°  0.697/_90.0°  0.67/_90.0°  0.763/_90.0°  0.67/_90.0°  
0.533/_90.0°  0.64/_90.0°  0.717/_90.0°  0.67/_90.0°  1.217/_90.0°  




array([[0.+0.717j, 0.+0.61j , 0.+0.533j, 0.+0.58j , 0.+0.533j],
       [0.+0.61j , 0.+0.732j, 0.+0.64j , 0.+0.697j, 0.+0.64j ],
       [0.+0.533j, 0.+0.64j , 0.+0.717j, 0.+0.67j , 0.+0.717j],
       [0.+0.58j , 0.+0.697j, 0.+0.67j , 0.+0.763j, 0.+0.67j ],
       [0.+0.533j, 0.+0.64j , 0.+0.717j, 0.+0.67j , 0.+1.217j]])

In [5]:
#ex 10
print("EXERCICIO 10")
nepo.Zbus_case4(zbus9, 0.2j, j=1, k=4)

EXERCICIO 10
CASO 4 - Adicionando Zb entre duas barras j e k existentes
Adicionando Zb=0.2j entre barras 1 e 4
Copiando linha j - linha k e coluna j - coluna k ao final da matriz
O ultimo elemento sera: Zthjk + Zb
Zthjk = Zbus[j][j] + Zbus[k][k] - 2*Zbus[j][k]
Zthjk = 0.6809/_90.0° + 0.6986/_90.0° + 1.2564/_90.0° = 0.32/_90.0°
Zthjk + Zb = 0.32/_90.0° + 0.2j = 0.6986/_90.0°

Zbus original:
0.717/_90.0°  0.61/_90.0°  0.533/_90.0°  0.58/_90.0°  
0.61/_90.0°  0.732/_90.0°  0.64/_90.0°  0.697/_90.0°  
0.533/_90.0°  0.64/_90.0°  0.717/_90.0°  0.67/_90.0°  
0.58/_90.0°  0.697/_90.0°  0.67/_90.0°  0.763/_90.0°  

Zbus final:
0.6809/_90.0°  0.6329/_90.0°  0.5691/_90.0°  0.6282/_90.0°  
0.6329/_90.0°  0.7174/_90.0°  0.6171/_90.0°  0.6664/_90.0°  
0.5691/_90.0°  0.6171/_90.0°  0.6809/_90.0°  0.6218/_90.0°  
0.6282/_90.0°  0.6664/_90.0°  0.6218/_90.0°  0.6986/_90.0°  




array([[0.+0.6809j, 0.+0.6329j, 0.+0.5691j, 0.+0.6282j],
       [0.+0.6329j, 0.+0.7174j, 0.+0.6171j, 0.+0.6664j],
       [0.+0.5691j, 0.+0.6171j, 0.+0.6809j, 0.+0.6218j],
       [0.+0.6282j, 0.+0.6664j, 0.+0.6218j, 0.+0.6986j]])

In [6]:
#ex 14
zbus3 = 1j*np.array([
    [0.15, 0.08, 0.04, 0.07],
    [0.08, 0.15, 0.06, 0.09],
    [0.04, 0.06, 0.13, 0.05],
    [0.07, 0.09, 0.05, 0.12]
])

In [7]:
#ex 15
ybus15 = 1j*np.array([
    [-12, 5, 2],
    [5, -7.5, 2.5],
    [2, 2.5, -8.5]
])

zbus15 = nepo.inv(ybus15)

In [8]:
#ex 17
zbus17 = 1j*np.array([
    [0.244, 0.194, 0.156, 0.146],
    [0.194, 0.23, 0.15, 0.15],
    [0.155, 0.15, 0.2, 0.105],
    [0.146, 0.15, 0.105, 0.196]
])
print("Exercicio 17")
nepo.triphase_fault_zbus(zbus17, k_fault=1, Vf=1)

Exercicio 17

Falta trifasica na barra k=1 com tensao pre-falta Vf de 1 pu
Zbus =
[[0.+0.244j 0.+0.194j 0.+0.156j 0.+0.146j]
 [0.+0.194j 0.+0.23j  0.+0.15j  0.+0.15j ]
 [0.+0.155j 0.+0.15j  0.+0.2j   0.+0.105j]
 [0.+0.146j 0.+0.15j  0.+0.105j 0.+0.196j]] 

Calculando If:
If = Vf/Zbus[1][1] = 1/0.23j = 4.0984/_-90.0°

Calculando as tensoes
V[j] = Vf - Zbus[j][1]*If 

Calculando as correntes entre as barras
(ex.: entre barra 1 e 2 é I[1][2]):
I[i][j] = (V[i] - V[j])/Zb[i][j]

Tensoes finais:
[[0.    +0.j]
 [0.2049+0.j]
 [0.3648+0.j]
 [0.4016+0.j]]

Correntes entre barras: 
[[0.+0.j     0.+1.6244j 0.+1.4583j 0.+1.037j ]
 [0.-1.6421j 0.+0.j     0.+0.5971j 0.+0.9404j]
 [0.-1.4063j 0.-0.6133j 0.+0.j     0.+0.0012j]
 [0.-1.0412j 0.-0.9423j 0.-0.0001j 0.+0.j    ]]



(array([0.    +0.j, 0.2049+0.j, 0.3648+0.j, 0.4016+0.j]),
 array([[0.+0.j    , 0.+1.6244j, 0.+1.4583j, 0.+1.037j ],
        [0.-1.6421j, 0.+0.j    , 0.+0.5971j, 0.+0.9404j],
        [0.-1.4063j, 0.-0.6133j, 0.+0.j    , 0.+0.0012j],
        [0.-1.0412j, 0.-0.9423j, 0.-0.0001j, 0.+0.j    ]]))

In [9]:

#ex 18
print("Exercicio 18")
nepo.fault_phase_gnd(0.15j, 0.15j, 0.05j, Zf=0, Vf=1)
#ex 19
print("Exercicio 19")
nepo.fault_phase_phase(0.15j, 0.15j, 0.05j, Zf=0, Vf=1)

Exercicio 18

Falta Fase-Terra com Vf=1.0/_0.0°pu, Zkk1=0.15j, Zkk2=0.15j, Zkk0=0.05j e Zf=0

Calculando Ifa0, Ifa1, Ifa2:
Ifa0 = Ifa1 = Ifa2 = Vf/(Zkk0+Zkk1+Zkk2+3*Zf)
Ifa0 = 1.0/_0.0°/(0.05j+0.15j+0.15j+0)
Ifa0 = 2.8571/_-90.0°

Calculando Ifa:
 Ifa = Ifa0 + Ifa1 + Ifa2 = 3*Ifa0 
 Ifa = 8.5714/_-90.0°

vIfn =
 [[0.-2.8571j]
 [0.-2.8571j]
 [0.-2.8571j]] 

 vIf =
[[0.-8.5714j]
 [0.+0.j    ]
 [0.+0.j    ]] 



Calculando tensoes pos falta:
Vka0 = -Zkk0*Ifa0
Vka1 = Vf - Zkk1*Ifa1
Vka2 = -Zkk2*Ifa2

Vkan = 
0.1429/_180.0°  
0.5714/_0.0°  
0.4286/_180.0°  

Vabc = (A @ Vkan) / sqrt(3) = 
0.0/_180.0°  
0.8921/_-103.9°  
0.8921/_103.9°  
Exercicio 19

Falta Fase-Fase com Vf=1.0/_0.0°pu, Zkk1=0.15j, Zkk2=0.15j e Zf=0

Calculando Ifa0, Ifa1, Ifa2:
Ifa0 = 0
Ifa1 = -Ifa2 = Vf/(Zkk1+Zkk2+Zf)
Ifa1 = 1.0/_0.0°/(0.15j+0.15j+0)
Ifa1 = 3.3333/_-90.0° = -Ifa2
Ifa2 = 3.3333/_90.0°

Calculando Ifa:
 Ifa = Ifa0 + Ifa1 + Ifa2 
 Ifa = 0.0/_0.0°

vIf =
0.0/_0.0°  
5.7735/_180.0°  
5.7735/_-0.0°  

vIfn =
0.0

(array([[ 0.    +0.j],
        [-5.7735+0.j],
        [ 5.7735-0.j]]),
 array([[0.+0.j    ],
        [0.-3.3333j],
        [0.+3.3333j]]),
 array([[ 1. +0.j],
        [-0.5+0.j],
        [-0.5+0.j]]),
 array([[0. -0.j],
        [0.5+0.j],
        [0.5-0.j]]))

In [10]:
# ex 21
print('Exercicio 21')
nepo.fault_phase_gnd(0.2j,0.2j,0.05j, Zf=0.08j,Vf=1)

Exercicio 21

Falta Fase-Terra com Vf=1.0/_0.0°pu, Zkk1=0.2j, Zkk2=0.2j, Zkk0=0.05j e Zf=0.08j

Calculando Ifa0, Ifa1, Ifa2:
Ifa0 = Ifa1 = Ifa2 = Vf/(Zkk0+Zkk1+Zkk2+3*Zf)
Ifa0 = 1.0/_0.0°/(0.05j+0.2j+0.2j+0.24j)
Ifa0 = 1.4493/_-90.0°

Calculando Ifa:
 Ifa = Ifa0 + Ifa1 + Ifa2 = 3*Ifa0 
 Ifa = 4.3478/_-90.0°

vIfn =
 [[0.-1.4493j]
 [0.-1.4493j]
 [0.-1.4493j]] 

 vIf =
[[0.-4.3478j]
 [0.+0.j    ]
 [0.+0.j    ]] 



Calculando tensoes pos falta:
Vka0 = -Zkk0*Ifa0
Vka1 = Vf - Zkk1*Ifa1
Vka2 = -Zkk2*Ifa2

Vkan = 
0.0725/_180.0°  
0.7101/_0.0°  
0.2899/_180.0°  

Vabc = (A @ Vkan) / sqrt(3) = 
0.3478/_0.0°  
0.911/_-108.07°  
0.911/_108.07°  


(array([[0.-4.3478j],
        [0.+0.j    ],
        [0.+0.j    ]]),
 array([[0.-1.4493j],
        [0.-1.4493j],
        [0.-1.4493j]]),
 array([[ 0.3478+0.j   ],
        [-0.2826-0.866j],
        [-0.2826+0.866j]]),
 array([[-0.0725+0.j],
        [ 0.7101+0.j],
        [-0.2899+0.j]]))